---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/vfarcic/devops-toolkit-crossplane.git
    targetRevision: HEAD
    path: apps
  destination:
    name: production
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
